### ISSUE TITLE
Display issues on Microsoft Edge

### ISSUE THREAD

**Issue by m90att** [steepleian/weewx-Weather34#5] opened 2019-12-05 16:29 UTC
Using Microsoft Edge browser (on Windows 10 S on Surface Go), there are minor display issues where the nationality flags can be seen on the left side of the screen.  Please see below.

![image](https://user-images.githubusercontent.com/56609577/70253958-25748c00-177c-11ea-9848-0c3a7387bb37.png)

![image](https://user-images.githubusercontent.com/56609577/70253971-2dccc700-177c-11ea-9df3-b8b4772ceab9.png)

![image](https://user-images.githubusercontent.com/56609577/70253986-36bd9880-177c-11ea-875f-ed31f84e8322.png)

![image](https://user-images.githubusercontent.com/56609577/70253990-3b824c80-177c-11ea-90ed-f207fd85ecd1.png)

![image](https://user-images.githubusercontent.com/56609577/70254001-40470080-177c-11ea-8b94-efe1abfdf1b1.png)

![image](https://user-images.githubusercontent.com/56609577/70254007-43da8780-177c-11ea-9631-65c4047d198e.png)

This is also seen in portrait mode:
![image](https://user-images.githubusercontent.com/56609577/70254036-51900d00-177c-11ea-937a-78ed2bcf2eec.png)

**Comment by steepleian** [comment] 2019-12-05 19:01
Hi Matt,

I cannot reproduce this is issue with Edge in Windows 10. I have tried 10 different Weather34 skin sites without any problem. I Have not been able to get to your site as the browser times out. Is it public at the moment! Unfortunately I do not have an Edge Go to use. What do you see when you go to my site at https://claydonsweather.org.uk ? This is currently a clean install from yesterday.

Thanks,
Ian

**Comment by m90att** [comment] 2019-12-06 07:56
Hi,

Interestingly your site displays correctly so maybe it’s something to do with my installation (again)!



My URL is: http://littleworthweather.duckdns.org:8080, give that a go.

Cheers,

Matt

**Comment by steepleian** [comment] 2019-12-06 08:25
Yes its showing the same for me in the current Edge but not in the
development version of Edge. Suggest you try a new install of the latest
version.

Cheers,
Ian

**Comment by m90att** [comment] 2019-12-06 08:27
Thanks Ian. Unfortunately Windows 10 S is locked down and I cannot install
anything that's not in the windows store. I suppose I shall have to wait
until it's pushed out as a public release.

**Comment by steepleian** [comment] 2019-12-06 08:43
I understand - corporate policy maybe?

**Comment by m90att** [comment] 2019-12-06 08:44
No, it's a personal device. It's Microsoft's own limitation.

**Comment by steepleian** [comment] 2019-12-06 08:44
But I meant the skin not Edge development version.

**Comment by steepleian** [comment] 2019-12-06 08:45
Closing as seems to be a problem with one specific installation

**Closed by steepleian** 2019-12-06 08:45 UTC
