### ISSUE TITLE
w34 install problem

### ISSUE THREAD

**Issue by belidi** [steepleian/weewx-Weather34#148] opened 2023-06-22 15:42 UTC
I have this problem and I don't know what to do
""
sudo python3 w34_installer.py
!!! THIS INSTALL IS USING PYTHON VERSION 3.9.2 IS THIS CORRECT? (Yes/No) y
Install will continue with Python Version 3.9.2

PYTHON EPHEM VERSION 4.1.4 INSTALLED
PHP 7.4.33 (cli) (built: Jun  9 2023 16:51:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
w34_installer Config file setup_py.conf was chosen.
IS THIS CORRECT? (Yes/No) y
!!! WEEWX HTML ROOT  /var/www/html  DOES NOT MATCH W34_INSTALLER www PATH.  /var/www/html/weewx  INSTALL ABORTED!!!
""

**Comment by Rayvenhaus** [comment] 2023-06-22 21:52
Hello belidi. Thank you for providing the complete error. This error is very straightforward.  The setup program compares what you've got set in your weewx.conf file for the HTML ROOT and what you've got set in your chosen configuration, in this case, setup_py.conf. 

In your case, the HTML ROOT in your weewx.conf and your setup_py.conf file do not match. As indicated, your weewx.conf is set to:
WEEWX HTML ROOT /var/www/html

whilst setup_py.conf is set to:
www PATH. /var/www/html/weewx

You'll need to edit the setup_py.conf file to match what is in your weewx.conf file.  Make sure you are following the installation guide [here](https://github.com/steepleian/weewx-Weather34/blob/main/INSTALLATION_GUIDE.md)

**Comment by Rayvenhaus** [comment] 2023-06-22 21:54
This issue is being closed as this is not a bug but an installation error.

**Closed as completed by Rayvenhaus** 2023-06-22 21:54 UTC
