### ISSUE TITLE
No data populate Home page

### ISSUE THREAD

**Issue by ornellino** [steepleian/weewx-Weather34#28] opened 2021-03-05 15:32 UTC
Hi, I have installed Weather34 one week ago, but in home page I don't see any data (no temp, no wind, no rain, ecc.), but if I select weekly or monthly, the graphics are populated correctly.
I have no errors in syslog neither in apache log.
![Immagine 2021-03-05 162705](https://user-images.githubusercontent.com/48414020/110136698-4806b200-7dd0-11eb-8e42-c5a96d46fe30.png)
![Immagine 2021-03-05 163219](https://user-images.githubusercontent.com/48414020/110136728-505eed00-7dd0-11eb-98b4-5f43e51b3080.png)
Tanks in advance for the support.
Andrea

**Comment by dgunnell** [comment] 2021-03-05 16:06
Search for any of the following below, line 2517 is the key indicator your looking for.  Check /var/log/messages, /var/log/user.log to see of those errors are there.  The latest update for checking existence of lightening variables caused the line 2517 error for me and the symptoms you are seeing.

Feb 8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Feb 8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/Weather34/serverdata/archivedata.php.tmpl
Feb 8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'format' while searching for 'format'
Feb 8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: **** Traceback (most recent call last):
Feb 8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: **** File "/home/weewx/bin/weewx/cheetahgenerator.py", line 324, in generate
Feb 8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: **** unicode_string = compiled_template.respond()
Feb 8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: **** File "_home_weewx_skins_Weather34_serverdata_archivedata_php_tmpl.py", line 2517, in respond
Feb 8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: **** NameMapper.NotFound: cannot find 'format' while searching for 'format'

**Comment by balloonhotair** [comment] 2021-03-05 19:23
In the development branch under skins/Weather34/serverdata use the file archivedata.php.tmpl and replace your current one after making a copy of it.

**Comment by steepleian** [comment] 2021-03-05 22:38
archivedata.php.tmpl correction merged into main branch

**Comment by ornellino** [comment] 2021-03-06 20:38
I haven't any /var/log/message or /var/log/user.log... the system is a virtual machine on a NAS with Ubuntu 18.04.5 LTS. In any case I renamed archivedata.php.tmpl and replaced with the new one in main branch, but it still has the same behavior.

**Comment by steepleian** [comment] 2021-03-06 21:11
Can you paste the contents of your archivedata.php file please

**Comment by ornellino** [comment] 2021-03-07 10:26
```
#errorCatcher Echo
##
## Specifying an encoding of UTF-8 is usually safe, but if your text is 
## actually in Latin-1, then you should replace the string "UTF-8" with "latin-1"
## If you do this, you should also change the 'Content-Type' metadata below.
#encoding UTF-8
##
<?php
##		Calculate lenght of daylight
	#set $daylenght = time.strftime('%H:%M', time.gmtime(int($almanac.sun.set.raw -  $almanac.sun.rise.raw)))
##		Truncate station uptime decimals
	#set $stationuptime = str($station.os_uptime.raw).split('.')[0] 	
##		Calculate Beaufort based on wind speed in knots
          #if $varExists('$current.windSpeed') and $current.windSpeed.raw is not None
          #if $unit.unit_type.windSpeed == 'mile_per_hour'
          #set $kts = $current.windSpeed.raw * 0.8689762
          #elif $unit.unit_type.windSpeed == 'km_per_hour'
            #set $kts = $current.windSpeed.raw * 0.539956
          #elif $unit.unit_type.windSpeed == 'meter_per_second'
            #set $kts = $current.windSpeed.raw * 1.943844
          #elif $unit.unit_type.windSpeed == 'knot'
            #set $kts = $current.windSpeed.raw
          #else
            #set $kts = 0
          #end if
          #if $kts < 1
            #set $beaufort = 0
          #elif $kts < 4
            #set $beaufort = 1
          #elif $kts < 7
            #set $beaufort = 2
          #elif $kts < 11
            #set $beaufort = 3
          #elif $kts < 17
            #set $beaufort = 4
          #elif $kts < 22
            #set $beaufort = 5
          #elif $kts < 28
            #set $beaufort = 6
          #elif $kts < 34
            #set $beaufort = 7
          #elif $kts < 41
            #set $beaufort = 8
          #elif $kts < 48
            #set $beaufort = 9
          #elif $kts < 56
            #set $beaufort = 10
          #elif $kts < 64
            #set $beaufort = 11
          #else
            #set $beaufort = 12
          #end if
          #else
            #set $beaufort = 'N/A'
          #end if
         #if $almanac.moon_phase.lower() == "New".lower()
            #set $moonphase = "0"
          #else if $almanac.moon_phase.lower() == "Waxing Crescent".lower()
            #set $moonphase = "1"
	  #else if $almanac.moon_phase.lower() == "First Quarter".lower()
            #set $moonphase = "2"
	  #else if $almanac.moon_phase.lower() == "Waxing Gibbous".lower()
            #set $moonphase = "3"
          #else if $almanac.moon_phase.lower() == "Full".lower()
            #set $moonphase = "4"
	  #else if $almanac.moon_phase.lower() == "Waning Gibbous".lower()
            #set $moonphase = "5"
	  #else if $almanac.moon_phase.lower() == "Last Quarter".lower()
            #set $moonphase = "6"
	  #else if $almanac.moon_phase.lower() == "Waning Crescent".lower()
            #set $moonphase = "7"
          #end if
          
      #import datetime
      #set $now = datetime.datetime.now()
      #set $nowHour = $now.hour
      #set $sunrise_hour = datetime.datetime.fromtimestamp($almanac.sunrise.raw).strftime('%H')
      #set $sunset_hour = datetime.datetime.fromtimestamp($almanac.sunset.raw).strftime('%H')
        ##if $sunrise_hour <= $nowHour < $sunset_hour ## This works but to keep it inline with JavaScript the below works too
        #if int($sunrise_hour) <= int($nowHour) and int($nowHour) < int($sunset_hour)
            #set $bodyTheme = "light"
            
        #else
            ## Night time, use dark mode
            #set $bodyTheme = "dark"
            
        #end if  

        #set $mlsc = "N/A"
        #if $varExists('month.lightning_strike_count') and $month.lightning_strike_count.sum is not None 
          #set $mlsc = $month.lightning_strike_count.sum.format(add_label=False, $localize=False) 
        #end if
        #set $ylsc = "N/A"
        #if $varExists('year.lightning_strike_count') and $year.lightning_strike_count.sum is not None 
          #set $ylsc = $year.lightning_strike_count.sum.format(add_label=False, $localize=False) 
        #end if
        #set $dysc = "N/A"
        #if $varExists('day.lightning_strike_count') and $day.lightning_strike_count.sum is not None 
          #set $dysc = $day.lightning_strike_count.sum.format(add_label=False, $localize=False) 
        #end if
        #set $ldlt = "N/A"
        #if $varExists('year.lightning_distance.lasttime') and $year.lightning_distance.lasttime is not None  
           #set $ldlt = $year.lightning_distance.lasttime
        #end if
  
          #import time
#set almost_end = $rainyear.end.raw - 1
#set almost_end_tt = $time.localtime($almost_end)
#######################SAME ORDER AS METEOBRIDGEAPI
$theme_switch = "$bodyTheme";
$weewxapi[17] = "$span($time_delta=300).windSpeed.avg.format(add_label=False, $localize=False)";
$weewxapi[18] = "$span($hour_delta=1).barometer.avg.format(add_label=False, $localize=False)";
$weewxapi[19] = "$month.rain.sum.format(add_label=False, $localize=False)";
$weewxapi[20] = "$rainyear.rain.sum.format(add_label=False, $localize=False)";
$weewxapi[21] = "$yesterday.rain.sum.format(add_label=False, $localize=False)";
$weewxapi[25] = "$span($hour_delta=1).outTemp.max.format(add_label=False, $localize=False)";
$weewxapi[26] = "$day.outTemp.max.format(add_label=False, $localize=False)";
$weewxapi[27] = "$day.outTemp.maxtime.format(format_string="%H:%M")";
$weewxapi[28] = "$day.outTemp.min.format(add_label=False, $localize=False)";  
$weewxapi[29] = "$day.outTemp.mintime.format(format_string="%H:%M")";
$weewxapi[30] = "$day.windSpeed.max.format(add_label=False, $localize=False)";
$weewxapi[31] = "$day.windSpeed.maxtime.format(format_string="%H:%M")";    
$weewxapi[32] = "$day.windGust.max.format(add_label=False, $localize=False)";
$weewxapi[33] = "$day.windGust.maxtime.format(format_string="%H:%M")";
$weewxapi[34] = "$day.barometer.max.format(add_label=False, $localize=False)";	
$weewxapi[35] = "$day.barometer.maxtime.format(format_string="%H:%M")";
$weewxapi[36] = "$day.barometer.min.format(add_label=False, $localize=False)";
$weewxapi[37] = "$day.barometer.mintime.format(format_string="%H:%M")";
## $daymaxintemp = "$day.inTemp.max.format(add_label=False, $localize=False)";
## $dayminintemp = "$day.inTemp.min.format(add_label=False, $localize=False)"; 
$weewxapi[40] = "$current.windGust.format(add_label=False, $localize=False)";
$weewxapi[41] = "$current.heatindex.format(add_label=False, $localize=False)";
$weewxapi[44] = "$span($hour_delta=24).rain.sum.format(add_label=False, $localize=False)";
$weewxapi[46] = "$span($time_delta=600).windDir.avg.format(add_label=False, $localize=False)";
$weewxapi[47] = "$span($hour_delta=1).rain.sum.format(add_label=False, $localize=False)";
$weewxapi[48] = "$month.dewpoint.max.format(add_label=False, $localize=False)";
$weewxapi[49] = "$month.dewpoint.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[50] = "$month.dewpoint.min.format(add_label=False, $localize=False)";
$weewxapi[51] = "$month.dewpoint.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[52] = "$yesterday.dewpoint.max.format(add_label=False, $localize=False)";
$weewxapi[53] = "$yesterday.dewpoint.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[54] = "$year.dewpoint.max.format(add_label=False, $localize=False)";
$weewxapi[55] = "$year.dewpoint.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[56] = "$year.dewpoint.min.format(add_label=False, $localize=False)";
$weewxapi[57] = "$year.dewpoint.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[58] = "$day.UV.max.format(add_label=False, $localize=False)";
$weewxapi[59] = "$day.outHumidity.max.format(add_label=False, $localize=False)";
$weewxapi[60] = "$day.outHumidity.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[61] = "$day.outHumidity.min.format(add_label=False, $localize=False)";
$weewxapi[62] = "$day.outHumidity.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[63] = "$day.dewpoint.max.format(add_label=False, $localize=False)";
$weewxapi[64] = "$day.dewpoint.maxtime.format(format_string="%Y%m%d%H%M%S")";  
$weewxapi[65] = "$day.dewpoint.min.format(add_label=False, $localize=False)";
$weewxapi[66] = "$day.dewpoint.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[67] = "$span(time_delta=900).outTemp.avg.format(add_label=False, $localize=False)";
$weewxapi[68] = "$span(time_delta=900).outHumidity.avg.format(add_label=False, $localize=False)";
$weewxapi[69] = "$span(time_delta=900).dewpoint.avg.format(add_label=False, $localize=False)";
$weewxapi[70] = "$span(time_delta=900).inTemp.avg.format(add_label=False, $localize=False)";
$weewxapi[71] = "$span(time_delta=900).inHumidity.avg.format(add_label=False, $localize=False)";
$weewxapi[72] = "$span($time_delta=900).windSpeed.avg.format(add_label=False, $localize=False)";
$weewxapi[73] = "$span($time_delta=1800).windSpeed.avg.format(add_label=False, $localize=False)";
$weewxapi[74] = "$mlsc";	
$weewxapi[75] = "$ylsc";	
$weewxapi[76] = "$dysc";	
$weewxapi[77] = "$ldlt";
$weewxapi[78] = "N/A";	
$weewxapi[79] = "N/A";
$weewxapi[80] = "$day.radiation.max.format(add_label=False, $localize=False)";
$weewxapi[81] = "$stationuptime";
$weewxapi[82] = "$yesterday.outTemp.max.format(add_label=False, $localize=False)";
$weewxapi[83] = "$yesterday.outTemp.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[84] = "$yesterday.outTemp.min.format(add_label=False, $localize=False)";
$weewxapi[85] = "$yesterday.outTemp.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[86] = "$month.outTemp.max.format(add_label=False, $localize=False)";
$weewxapi[87] = "$month.outTemp.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[88] = "$month.outTemp.min.format(add_label=False, $localize=False)";
$weewxapi[89] = "$month.outTemp.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[90] = "$year.outTemp.max.format(add_label=False, $localize=False)";
$weewxapi[91] = "$year.outTemp.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[92] = "$year.outTemp.min.format(add_label=False, $localize=False)";
$weewxapi[93] = "$year.outTemp.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[94] = "$yesterday.windGust.max.format(add_label=False, $localize=False)";
$weewxapi[95] = "$yesterday.windGust.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[96] = "$month.windGust.max.format(add_label=False, $localize=False)";
$weewxapi[97] = "$month.windGust.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[98] = "$year.windGust.max.format(add_label=False, $localize=False)";
$weewxapi[99] = "$year.windGust.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[100] = "$yesterday.rainRate.max.format(add_label=False, $localize=False)";
$weewxapi[101] = "$month.rainRate.max.format(add_label=False, $localize=False)";
$weewxapi[102] = "$month.rainRate.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[103] = "$rainyear.rainRate.max.format(add_label=False, $localize=False)";
$weewxapi[104] = "$rainyear.rainRate.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[105] = "$day.radiation.max.format(add_label=False, $localize=False)";
$weewxapi[106] = "$day.radiation.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[107] = "$yesterday.radiation.max.format(add_label=False, $localize=False)";
$weewxapi[108] = "$yesterday.radiation.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[109] = "$month.radiation.max.format(add_label=False, $localize=False)";
$weewxapi[110] = "$month.radiation.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[111] = "$year.radiation.max.format(add_label=False, $localize=False)";
$weewxapi[112] = "$year.radiation.maxtime.format(format_string="%Y%m%d%H%M%S")";
## $weewxapi[x] = "$day.UV.max.format(add_label=False, $localize=False)";
$weewxapi[113] = "$day.UV.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[114] = "$yesterday.UV.max.format(add_label=False, $localize=False)";
$weewxapi[115] = "$yesterday.UV.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[116] = "$month.UV.max.format(add_label=False, $localize=False)";
$weewxapi[117] = "$month.UV.maxtime.format(format_string="%Y%m%d%H%M%S")"; 
$weewxapi[118] = "$year.UV.max.format(add_label=False, $localize=False)";
$weewxapi[119] = "$year.UV.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[120] = "$yesterday.dewpoint.min.format(add_label=False, $localize=False)";
$weewxapi[121] = "$yesterday.dewpoint.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[122] = "$latest.dateTime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[123] = "$span($hour_delta=1).outTemp.avg.format(add_label=False, $localize=False)";
$weewxapi[124] = "$last_rain.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[125] = "$alltime.outTemp.max.format(add_label=False, $localize=False)";
$weewxapi[126] = "$alltime.outTemp.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[127] = "$alltime.outTemp.min.format(add_label=False, $localize=False)";
$weewxapi[128] = "$alltime.outTemp.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[129] = "$alltime.dewpoint.max.format(add_label=False, $localize=False)";
$weewxapi[130] = "$alltime.dewpoint.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[131] = "$alltime.dewpoint.min.format(add_label=False, $localize=False)";
$weewxapi[132] = "$alltime.dewpoint.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[133] = "$alltime.windGust.max.format(add_label=False, $localize=False)";
$weewxapi[134] = "$alltime.windGust.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[135] = "$yesterday.barometer.max.format(add_label=False, $localize=False)";
$weewxapi[136] = "$yesterday.barometer.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[137] = "$yesterday.barometer.min.format(add_label=False, $localize=False)";
$weewxapi[138] = "$yesterday.barometer.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[139] = "$month.barometer.max.format(add_label=False, $localize=False)";	
$weewxapi[140] = "$month.barometer.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[141] = "$month.barometer.min.format(add_label=False, $localize=False)";	
$weewxapi[142] = "$month.barometer.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[143] = "$year.barometer.max.format(add_label=False, $localize=False)";	
$weewxapi[144] = "$year.barometer.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[145] = "$year.barometer.min.format(add_label=False, $localize=False)";	
$weewxapi[146] = "$year.barometer.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[147] = "$alltime.barometer.max.format(add_label=False, $localize=False)";		
$weewxapi[148] = "$alltime.barometer.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[149] = "$alltime.barometer.min.format(add_label=False, $localize=False)";
$weewxapi[150] = "$alltime.barometer.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[151] = "$alltime.rain.sum.format(add_label=False, $localize=False)";
$weewxapi[152] = "$day.outTemp.avg.format(add_label=False, $localize=False)";
$weewxapi[153] = "$moonphase";
$weewxapi[154] = "$almanac.moon_fullness";
$weewxapi[155] = "$daylenght";
$weewxapi[156] = "$almanac.moon.rise.format(format_string="%H:%M")";
$weewxapi[157] = "$almanac.moon.set.format(format_string="%H:%M")";
$weewxapi[158] = "$day.windSpeed.avg.format(add_label=False, $localize=False)";
$weewxapi[159] = "$month.outHumidity.max.format(add_label=False, $localize=False)";
$weewxapi[160] = "$month.outHumidity.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[161] = "$month.outHumidity.min.format(add_label=False, $localize=False)";
$weewxapi[162] = "$month.outHumidity.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[163] = "$year.outHumidity.max.format(add_label=False, $localize=False)";
$weewxapi[164] = "$year.outHumidity.maxtime.format(format_string="%Y%m%d%H%M%S")";	
$weewxapi[165] = "$year.outHumidity.min.format(add_label=False, $localize=False)";	
$weewxapi[166] = "$year.outHumidity.mintime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[167] = "$yesterday.outHumidity.max.format(add_label=False, $localize=False)";
$weewxapi[168] = "$yesterday.outHumidity.maxtime.format(format_string="%Y%m%d%H%M%S")";
$weewxapi[169] = "$yesterday.outHumidity.min.format(add_label=False, $localize=False)";	
$weewxapi[170] = "$yesterday.outHumidity.mintime.format(format_string="%Y%m%d%H%M%S")";  
$weewxapi[200] = "$current.windrun.format(add_label=False, $localize=False)";
$weewxapi[201] = "$span($time_delta=3600).windGust.max.format(add_label=False, $localize=False)";
$weewxapi[202] = "$span($hour_delta=3).rain.sum.format(add_label=False, $localize=False)";
$weewxapi[203] = "$current.cloudbase.format(add_label=False, $localize=False)";
$weewxapi[204] = "$current.signal8.format("%.0f")";
$weewxapi[205] = "$current.appTemp.format(add_label=False, $localize=False)";
$startcivil = "$almanac(horizon=-6).sun(use_center=1).rise.raw";
$endcivil = "$almanac(horizon=-6).sun(use_center=1).set.raw";
$rain_year_start = "$rainyear.start.format(format_string="%b -")";
$rain_year_end = "$time.strftime("%b", $almost_end_tt)";	
$daymaxrainrate = "$day.rainRate.max.format(add_label=False, $localize=False)";
$daymaxrainratetime = "$day.rainRate.maxtime.format(format_string="%Y%m%d%H%M%S")";
$yesterdaymaxrainratetime = "$yesterday.rainRate.maxtime.format(format_string="%Y%m%d%H%M%S")";
$alltimemaxrainrate = "$alltime.rainRate.max.format(add_label=False, $localize=False)";
$alltimemaxrainratetime = "$alltime.rainRate.maxtime.format(format_string="%Y%m%d%H%M%S")";
$yesterdaymaxwind = "$yesterday.windSpeed.max.format(add_label=False, $localize=False)";
$yesterdaymaxwindtime = "$yesterday.windSpeed.maxtime.format(format_string="%Y%m%d%H%M%S")";
$monthmaxwind = "$month.windSpeed.max.format(add_label=False, $localize=False)";
$monthmaxwindtime = "$month.windSpeed.maxtime.format(format_string="%Y%m%d%H%M%S")";
$yearmaxwind = "$year.windSpeed.max.format(add_label=False, $localize=False)";
$yearmaxwindtime = "$year.windSpeed.maxtime.format(format_string="%Y%m%d%H%M%S")";
## $current_windchill = "$current.windchill.format(add_label=False, $localize=False)";   
## $current_heatindex = "$current.heatindex.format(add_label=False, $localize=False)";
?>


```

**Comment by steepleian** [comment] 2021-03-07 10:49
That’s the template file. I need to see the generated archivedata.php file
which you will find in the server data folder.

**Comment by ornellino** [comment] 2021-03-07 10:54
I haven't!
But I after the change of template I found this error in syslog:
```
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'FileNotFoundError'>'
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Weather34/serverdata/archivedata.php.tmpl
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: **** Reason: [Errno 2] No such file or directory: '/etc/weewx/skins/Weather34/serverdata/archivedata.php.tmpl'
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 320, in generate
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****      filtersLib=weewx.cheetahgenerator)
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****    File "/usr/local/lib/python3.6/dist-packages/Cheetah/Template.py", line 1337, in __init__
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****      self._compile(source, file, compilerSettings=compilerSettings)
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****    File "/usr/local/lib/python3.6/dist-packages/Cheetah/Template.py", line 1631, in _compile
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****      self._fileMtime = os.path.getmtime(file)
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****      return os.stat(filename).st_mtime
Mar  7 11:50:28 jacuweather weewx[20006] ERROR weewx.cheetahgenerator: ****  FileNotFoundError: [Errno 2] No such file or directory: '/etc/weewx/skins/Weather34/serverdata/archivedata.php.tmpl'

```

**Comment by steepleian** [comment] 2021-03-07 11:02
Ok so where is the tmpl file on your system? Is your weewx installation by
setup.py or DEB package?

**Comment by ornellino** [comment] 2021-03-07 11:08
Sorry, my error in rename file....
Now I have this error:
```
Mar  7 12:05:43 jacuweather weewx[28729] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar  7 12:05:43 jacuweather weewx[28729] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Weather34/serverdata/archivedata.php.tmpl
Mar  7 12:05:43 jacuweather weewx[28729] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'format' while searching for 'format'
Mar  7 12:05:43 jacuweather weewx[28729] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  7 12:05:43 jacuweather weewx[28729] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 324, in generate
Mar  7 12:05:43 jacuweather weewx[28729] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Mar  7 12:05:43 jacuweather weewx[28729] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Weather34_serverdata_archivedata_php_tmpl.py", line 2503, in respond
Mar  7 12:05:43 jacuweather weewx[28729] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'format' while searching for 'format'

```

**Comment by steepleian** [comment] 2021-03-07 13:47
It does not appear that you have the most recent version of archivedata.php.tmpl. Try this one: -


[archivedata.php.tmpl.zip](https://github.com/steepleian/weewx-Weather34/files/6097219/archivedata.php.tmpl.zip)

**Comment by dgunnell** [comment] 2021-03-07 13:51
The code change I pasted below is causing the error related to line 2517 format........  I reverted back one version on this file and it corrected the problem so the new lightening variable missing check, etc. is not working right.

        #set $mlsc = "N/A"
        #if $varExists('month.lightning_strike_count') and $month.lightning_strike_count.sum is not None 
          #set $mlsc = $month.lightning_strike_count.sum.format(add_label=False, $localize=False) 
        #end if
        #set $ylsc = "N/A"
        #if $varExists('year.lightning_strike_count') and $year.lightning_strike_count.sum is not None 
          #set $ylsc = $year.lightning_strike_count.sum.format(add_label=False, $localize=False) 
        #end if
        #set $dysc = "N/A"
        #if $varExists('day.lightning_strike_count') and $day.lightning_strike_count.sum is not None 
          #set $dysc = $day.lightning_strike_count.sum.format(add_label=False, $localize=False) 
        #end if
        #set $ldlt = "N/A"
        #if $varExists('year.lightning_distance.lasttime') and $year.lightning_distance.lasttime is not None  
           #set $ldlt = $year.lightning_distance.lasttime
        #end if

**Comment by ornellino** [comment] 2021-03-07 13:59
> It does not appear that you have the most recent version of archivedata.php.tmpl. Try this one: -
> 
> [archivedata.php.tmpl.zip](https://github.com/steepleian/weewx-Weather34/files/6097219/archivedata.php.tmpl.zip)

With this one same error

**Comment by ornellino** [comment] 2021-03-07 14:02
@dgunnell so what i have to do? I have to replace the code? at what line?

**Comment by steepleian** [comment] 2021-03-07 14:35
Find the location of your existing archivedata.php.tmpl file and rename it to something different.
Un zip the file I attached in my last comment and place it in the same folder as a replacement.
Wait until your next archive interval has completed and check that a new archivedata.php file has been created in the weather34/serverdata folder of your webserver.

**Comment by dgunnell** [comment] 2021-03-07 16:00
On the new lightning check code looks like double quotes are missing on setting the variables.  I am not using lightning features so my version needs to be tested with someone using lightning before adding changes to development branch.  #set @mslc = ... is first occurrence where I added quotes and so on.  Here is my version with the quotes added:

        #set $mlsc = "N/A"
        #if $varExists('month.lightning_strike_count') and $month.lightning_strike_count.sum is not None 
          #set $mlsc = "$month.lightning_strike_count.sum.format(add_label=False, $localize=False)" 
        #end if
        #set $ylsc = "N/A"
        #if $varExists('year.lightning_strike_count') and $year.lightning_strike_count.sum is not None 
          #set $ylsc = "$year.lightning_strike_count.sum.format(add_label=False, $localize=False)" 
        #end if
        #set $dysc = "N/A"
        #if $varExists('day.lightning_strike_count') and $day.lightning_strike_count.sum is not None 
          #set $dysc = "$day.lightning_strike_count.sum.format(add_label=False, $localize=False)" 
        #end if
        #set $ldlt = "N/A"
        #if $varExists('year.lightning_distance.lasttime') and $year.lightning_distance.lasttime is not None  
           #set $ldlt = "$year.lightning_distance.lasttime"
        #end if

**Comment by ornellino** [comment] 2021-03-07 16:10
@steepleian I did it, but no difference.
@dgunnell It works! I added quotes and now everything work fine! Tanks!

**Comment by balloonhotair** [comment] 2021-03-08 03:20
Using quotes is incorrect. It is just masking the issue by changing the value to a string which will not work if a user wanted lightning data.
Would need to know what fields are in the database for lightning data for starts.

**Comment by dgunnell** [comment] 2021-03-08 12:53
Quotes may very well be incorrect.  The bottom line is not everyone has lightning data in their database because they are not tracking lightning nor do they care to.  THE real problem is the check for lightning data missing and then simply setting values to STRING "NA" is NOT working.  I suspect the variables do in fact exist AND are not equal to NONE so as a result the code tries to set the variables or something is wrong with the format().  Ornellino and I do not have the lightning data in the weewx database and I went into database to confirm.

**Comment by steepleian** [comment] 2021-03-08 14:40
Can you confirm if you are using the extended database schema which was introduced with version 4.0.0 of WeeWX or if you are using the previous standard which was based on Wview?
I am am using two setups, both using the extended schema. One setup has a lightning sensor, but the other does not - I have not been able to replicate the error that you are getting.

**Comment by dgunnell** [comment] 2021-03-08 15:54
Upgraded from 3.9.x to 4.4.0 awhile back.  I noticed my weewx.conf has  schema = schemas.wview_extended.schema
 in it but the database is clearly missing all the extended fields.  It seems that setup.py for weewx during upgrade did not upgrade the database itself.

**Comment by steepleian** [comment] 2021-03-08 16:29
OK, that line in weewx.conf only works if there is no database present. If you performed an in place upgrade, it would have ignored that line to protect your old database.

I am wondering whether this is the reason that I cannot replicate the error?

**Comment by dgunnell** [comment] 2021-03-08 16:37
I suspect this is why you cannot reproduce it.  If I recall doing a wee_database --reconfigure will upgrade my database?  If so, I can try that and confirm if new extended fields exist and then revert back to original archivedata.php.tmpl and see if it stops the problem?

**Comment by steepleian** [comment] 2021-03-08 17:22
Ok, thank you I look forward to your results.

**Comment by dgunnell** [comment] 2021-03-08 18:33
Reconfigured database and confirmed extended fields are now present.  Reverted back to original archivedata.php.tmpl from current version in git and is now running without errors.

**Comment by steepleian** [comment] 2021-03-08 23:01
Thank you for your peserverence. I have amended the installation guide with instructions on converting the database to the extended schema.

**Closed as completed by steepleian** 2021-03-08 23:01 UTC
